x= input('Write something: ')
print('Is x an alpha? ', x .isalpha())
print('Is x numeric? ', x .isnumeric())
print('Is x a number or an alpha? ', x .isalnum())
print('Is x  lower? ', x .islower())
print('Is x upper', x .isupper())