 #Tabuada=
x= int(input('Digite um número: '))
print('A tabuada de {} é: '.format(x))
print('-'*12)
print(x,'X {:2} = {:2}'.format(1,(x*1)))
print(x,'X {:2} = {:2}'.format(2,(x*2)))
print(x,'X {:2} = {:2}'.format(3,(x*3)))
print(x,'X {:2} = {:2}'.format(4,(x*4)))
print(x,'X {:2} = {:2}'.format(5,(x*5)))
print(x,'X {:2} = {:2}'.format(6,(x*6)))
print(x,'X {:2} = {:2}'.format(7,(x*7)))
print(x,'X {:2} = {:2}'.format(8,(x*8)))
print(x,'X {:2} = {:2}'.format(9,(x*9)))
print(x,'X {:2} = {:2}'.format(10,(x*10)))
print('-'*12)
